[tox]
envlist = py310, py311, py312, py313, linting, typing
isolated_build = True

[testenv]
deps =
    pytest>=7.0
    pytest-cov
commands =
    pytest {posargs:tests} --cov=pytest_do_not_mock --cov-report=term-missing

[testenv:linting]
skip_install = True
deps = ruff
commands =
    ruff check src tests
    ruff format --check src tests

[testenv:typing]
deps =
    mypy
    pyright
    pytest
commands =
    mypy src
    pyright src
